package provider

import (
	"context"
	"errors"
	"strings"

	"github.com/hashicorp/terraform-plugin-framework/resource"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/booldefault"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/planmodifier"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/stringplanmodifier"
	"github.com/hashicorp/terraform-plugin-framework/types"

	"github.com/deevnet/terraform-provider-deevnet/internal/client"
)

// A tenant's MQTT account on the platform broker (ADR-0012 §3, §8, §10).
// One account per thing that connects: a device, or a tenant workload.
type iotBrokerAccountResource struct{ client *client.Client }

func NewIoTBrokerAccountResource() resource.Resource { return &iotBrokerAccountResource{} }

type iotBrokerAccountModel struct {
	Tenant   types.String `tfsdk:"tenant"`
	Name     types.String `tfsdk:"name"`
	Device   types.String `tfsdk:"device"`
	Username types.String `tfsdk:"username"`
	// Publish and Subscribe are the tenant's own, RELATIVE patterns.
	Publish   types.List `tfsdk:"publish"`
	Subscribe types.List `tfsdk:"subscribe"`
	// GrantedPublish and GrantedSubscribe are the same patterns as the broker
	// holds them: absolute, with the tenant prefix the API wrote.
	GrantedPublish   types.List   `tfsdk:"granted_publish"`
	GrantedSubscribe types.List   `tfsdk:"granted_subscribe"`
	Password         types.String `tfsdk:"password"`
	Status           types.String `tfsdk:"status"`
	Present          types.Bool   `tfsdk:"present"`
}

func (r *iotBrokerAccountResource) Metadata(_ context.Context, req resource.MetadataRequest, resp *resource.MetadataResponse) {
	resp.TypeName = req.ProviderTypeName + "_iot_broker_account"
}

func (r *iotBrokerAccountResource) Schema(_ context.Context, _ resource.SchemaRequest, resp *resource.SchemaResponse) {
	resp.Schema = schema.Schema{
		MarkdownDescription: "An MQTT account on the platform broker, for one of the tenant's " +
			"devices or workloads.\n\n" +
			"Configure the client with `username` and `password`.\n\n" +
			"**Replacing this resource issues a new password, and anything already holding the " +
			"old one stops connecting.** A rebuilt API does not do that: it restores the account " +
			"from this state. Use `-replace` only when you mean to revoke.",
		Attributes: map[string]schema.Attribute{
			"tenant": schema.StringAttribute{
				Required:            true,
				MarkdownDescription: "The tenant this broker account belongs to: the `name` of a `deevnet_tenant`.",
				PlanModifiers:       []planmodifier.String{stringplanmodifier.RequiresReplace()},
			},
			"name": schema.StringAttribute{
				Required:            true,
				MarkdownDescription: "A label for the account, unique within the tenant.",
				PlanModifiers:       []planmodifier.String{stringplanmodifier.RequiresReplace()},
			},
			"device": schema.StringAttribute{
				Optional: true,
				MarkdownDescription: "A device in the tenant's registry, in trust class `iot`. " +
					"Omit for an account a tenant workload uses. `iot_vendor` is refused: the " +
					"standard forbids those devices reaching the broker at all, so the account " +
					"could never be used.",
			},
			"publish": schema.ListAttribute{
				Optional:    true,
				ElementType: types.StringType,
				MarkdownDescription: "Topic patterns this account may publish to, **relative to " +
					"the tenant**: write `lightstand/+/scene`, not `eds/lightstand/+/scene`. The " +
					"API writes the prefix, which is what confines a tenant to its own topics.\n\n" +
					"May be omitted for an account that only subscribes. Omitting both is an " +
					"error: the account could do nothing.",
			},
			"subscribe": schema.ListAttribute{
				Optional:            true,
				ElementType:         types.StringType,
				MarkdownDescription: "Topic patterns this account may subscribe to, relative to the tenant. `#` means the tenant's whole tree, and no more.",
			},
			"granted_publish": schema.ListAttribute{
				Computed:            true,
				ElementType:         types.StringType,
				MarkdownDescription: "What the broker actually enforces: the publish patterns with the tenant prefix written in.",
			},
			"granted_subscribe": schema.ListAttribute{
				Computed:            true,
				ElementType:         types.StringType,
				MarkdownDescription: "What the broker actually enforces: the subscribe patterns with the tenant prefix written in.",
			},
			"username": computedString("The username to configure the client with. Derived by the API as `<tenant>-<name>`."),
			"status":   computedString("`ready` once the account is on the broker."),
			"password": schema.StringAttribute{
				Computed:  true,
				Sensitive: true,
				MarkdownDescription: "The password to configure the client with. Generated by the " +
					"API, which keeps only a hash of it — **this state is the only copy**.",
				PlanModifiers: []planmodifier.String{stringplanmodifier.UseStateForUnknown()},
			},
			"present": schema.BoolAttribute{
				Computed:            true,
				Default:             booldefault.StaticBool(true),
				MarkdownDescription: "Whether the API still holds this account.",
			},
		},
	}
}

func (r *iotBrokerAccountResource) Configure(_ context.Context, req resource.ConfigureRequest, resp *resource.ConfigureResponse) {
	r.client = clientFrom(req.ProviderData, &resp.Diagnostics)
}

// ModifyPlan turns "this account is not on the broker" into a diff, the way the
// Wi-Fi key resource does - otherwise an apply after the registry was lost, or
// after a create that failed at the writer, reports no changes and the account
// stays unwritten.
//
// Two conditions, not one. present=false is the registry having lost it.
// status != ready is the API holding a record the broker never received, which
// is what a 502 leaves behind - and without this, that account would sit in
// state looking settled and never be retried.
//
// password is NOT blanked, for the same reason the Wi-Fi key's psk is not: the
// value in state is the credential the clients were configured with, so
// leaving it known carries it into the apply and the broker is made to match
// the clients. Blanking it would mint a new password and every client holding
// the old one would stop connecting (ADR-0012 §5).
func (r *iotBrokerAccountResource) ModifyPlan(ctx context.Context, req resource.ModifyPlanRequest, resp *resource.ModifyPlanResponse) {
	if req.State.Raw.IsNull() || req.Plan.Raw.IsNull() {
		return
	}
	var state iotBrokerAccountModel
	resp.Diagnostics.Append(req.State.Get(ctx, &state)...)
	if resp.Diagnostics.HasError() {
		return
	}
	lost := state.Present.Equal(types.BoolValue(false)) ||
		!state.Status.Equal(types.StringValue("ready"))
	if !lost {
		return
	}
	var plan iotBrokerAccountModel
	resp.Diagnostics.Append(req.Plan.Get(ctx, &plan)...)
	if resp.Diagnostics.HasError() {
		return
	}
	plan.Present = types.BoolUnknown()
	plan.Status = types.StringUnknown()
	plan.Username = types.StringUnknown()
	plan.GrantedPublish = types.ListUnknown(types.StringType)
	plan.GrantedSubscribe = types.ListUnknown(types.StringType)
	resp.Diagnostics.Append(resp.Plan.Set(ctx, plan)...)
}

func (r *iotBrokerAccountResource) Create(ctx context.Context, req resource.CreateRequest, resp *resource.CreateResponse) {
	var plan iotBrokerAccountModel
	resp.Diagnostics.Append(req.Plan.Get(ctx, &plan)...)
	if resp.Diagnostics.HasError() {
		return
	}
	resp.Diagnostics.Append(r.put(ctx, plan, &resp.State)...)
}

func (r *iotBrokerAccountResource) Update(ctx context.Context, req resource.UpdateRequest, resp *resource.UpdateResponse) {
	var plan iotBrokerAccountModel
	resp.Diagnostics.Append(req.Plan.Get(ctx, &plan)...)
	if resp.Diagnostics.HasError() {
		return
	}
	resp.Diagnostics.Append(r.put(ctx, plan, &resp.State)...)
}

// Read never removes the resource from state: this state holds the only copy of
// the password, so dropping it would lose the credential for good. It records
// that the API no longer has the account, and ModifyPlan turns that into an
// apply that puts it back.
func (r *iotBrokerAccountResource) Read(ctx context.Context, req resource.ReadRequest, resp *resource.ReadResponse) {
	var state iotBrokerAccountModel
	resp.Diagnostics.Append(req.State.Get(ctx, &state)...)
	if resp.Diagnostics.HasError() {
		return
	}
	a, err := r.client.GetBrokerAccount(ctx, state.Tenant.ValueString(), state.Name.ValueString())
	switch {
	case errors.Is(err, client.ErrNotFound):
		state.Present = types.BoolValue(false)
		resp.Diagnostics.Append(resp.State.Set(ctx, state)...)
		return
	case err != nil:
		resp.Diagnostics.AddError("Reading the broker account failed", err.Error())
		return
	}
	// A read does not return the password, so the one in state is kept.
	m, diags := brokerAccountFrom(ctx, a, state)
	resp.Diagnostics.Append(diags...)
	if resp.Diagnostics.HasError() {
		return
	}
	resp.Diagnostics.Append(resp.State.Set(ctx, m)...)
}

func (r *iotBrokerAccountResource) Delete(ctx context.Context, req resource.DeleteRequest, resp *resource.DeleteResponse) {
	var state iotBrokerAccountModel
	resp.Diagnostics.Append(req.State.Get(ctx, &state)...)
	if resp.Diagnostics.HasError() {
		return
	}
	err := r.client.DeleteBrokerAccount(ctx, state.Tenant.ValueString(), state.Name.ValueString())
	if err != nil && !errors.Is(err, client.ErrNotFound) {
		resp.Diagnostics.AddError("Revoking the broker account failed", err.Error())
	}
}

func (r *iotBrokerAccountResource) put(ctx context.Context, m iotBrokerAccountModel, state stateSetter) diagList {
	var diags diagList
	pub, d := stringsFrom(ctx, m.Publish)
	diags.Append(d...)
	sub, d := stringsFrom(ctx, m.Subscribe)
	diags.Append(d...)
	if diags.HasError() {
		return diags
	}
	req := client.PutBrokerAccountRequest{
		Name:      m.Name.ValueString(),
		Device:    m.Device.ValueString(),
		Publish:   pub,
		Subscribe: sub,
	}
	// Send the password we already hold, so the API adopts it rather than
	// minting a new one. Empty on a first apply, which is when it generates one.
	if !m.Password.IsUnknown() && !m.Password.IsNull() {
		req.Password = m.Password.ValueString()
	}

	a, err := r.client.PutBrokerAccount(ctx, m.Tenant.ValueString(), req)
	if err != nil {
		diags.AddError("Issuing the broker account failed", err.Error())
		// A failure that still carried the account is the writer step having
		// failed after the API wrote its own record. Keep it - with its
		// password, which exists nowhere else - so the next apply supplies the
		// same one instead of stranding every client configured with it.
		//
		// The framework records state set here even though this call errors,
		// and the account's status is not "ready", so ModifyPlan plans the
		// retry rather than leaving it looking settled.
		if a.Name == "" {
			return diags
		}
		partial, d := brokerAccountFrom(ctx, a, m)
		diags.Append(d...)
		if diags.HasError() {
			return diags
		}
		diags.Append(state.Set(ctx, partial)...)
		return diags
	}

	out, d := brokerAccountFrom(ctx, a, m)
	diags.Append(d...)
	if diags.HasError() {
		return diags
	}
	return append(diags, state.Set(ctx, out)...)
}

// brokerAccountFrom folds an API answer into the model.
//
// The patterns need care. Config holds them relative and the API answers
// absolute, so writing the answer straight back would make every apply report
// an inconsistent result. Instead the prefix is stripped back off, which round
// trips exactly on a create AND makes a grant that drifted on the broker show
// up as a diff against the configuration - which recording only the absolute
// form would not.
func brokerAccountFrom(ctx context.Context, a client.BrokerAccount, prior iotBrokerAccountModel) (iotBrokerAccountModel, diagList) {
	var diags diagList
	tenant := a.Tenant
	if tenant == "" {
		tenant = prior.Tenant.ValueString()
	}

	pub, d := relativeList(ctx, tenant, a.Publish, prior.Publish)
	diags.Append(d...)
	sub, d := relativeList(ctx, tenant, a.Subscribe, prior.Subscribe)
	diags.Append(d...)
	grantedPub, d := absoluteList(ctx, a.Publish)
	diags.Append(d...)
	grantedSub, d := absoluteList(ctx, a.Subscribe)
	diags.Append(d...)
	if diags.HasError() {
		return iotBrokerAccountModel{}, diags
	}

	password := prior.Password
	if a.Password != "" {
		password = types.StringValue(a.Password)
	}
	if password.IsUnknown() {
		// A create whose answer carried no password should not leave an
		// unknown in state; the framework refuses to store one.
		password = types.StringNull()
	}
	device := prior.Device
	if a.Device != "" {
		device = types.StringValue(a.Device)
	}

	return iotBrokerAccountModel{
		Tenant:           types.StringValue(tenant),
		Name:             types.StringValue(a.Name),
		Device:           device,
		Username:         types.StringValue(a.Username),
		Publish:          pub,
		Subscribe:        sub,
		GrantedPublish:   grantedPub,
		GrantedSubscribe: grantedSub,
		Password:         password,
		Status:           types.StringValue(a.Status),
		Present:          types.BoolValue(true),
	}, diags
}

// relativeList renders the API's absolute patterns the way the configuration
// writes them. An empty answer keeps the configuration's own null/[] shape, so
// an account that declares no subscribe patterns does not gain an attribute it
// never wrote.
func relativeList(ctx context.Context, tenant string, abs []string, prior types.List) (types.List, diagList) {
	rel := make([]string, 0, len(abs))
	prefix := tenant + "/"
	for _, p := range abs {
		// A pattern that is not under the prefix cannot happen - the API
		// writes it - but if it ever does, keep it verbatim rather than
		// silently reporting something the broker is not enforcing.
		rel = append(rel, strings.TrimPrefix(p, prefix))
	}
	if len(rel) == 0 && prior.IsNull() {
		return types.ListNull(types.StringType), nil
	}
	return types.ListValueFrom(ctx, types.StringType, rel)
}

func absoluteList(ctx context.Context, abs []string) (types.List, diagList) {
	if abs == nil {
		abs = []string{}
	}
	return types.ListValueFrom(ctx, types.StringType, abs)
}

// stringsFrom reads a configured list. A null or unknown list is no patterns,
// which is legitimate on one side: a sensor only publishes.
func stringsFrom(ctx context.Context, l types.List) ([]string, diagList) {
	if l.IsNull() || l.IsUnknown() {
		return nil, nil
	}
	var out []string
	diags := l.ElementsAs(ctx, &out, false)
	return out, diags
}
