package provider

import (
	"context"
	"errors"

	"github.com/hashicorp/terraform-plugin-framework/resource"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/booldefault"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/planmodifier"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/stringplanmodifier"
	"github.com/hashicorp/terraform-plugin-framework/types"

	"github.com/deevnet/terraform-provider-deevnet/internal/client"
)

// A tenant's Wi-Fi key for one IoT trust class (ADR-0012 §3). One key serves
// every device the tenant flashes with it; the substrate does not know those
// devices individually.
type iotWiFiKeyResource struct{ client *client.Client }

func NewIoTWiFiKeyResource() resource.Resource { return &iotWiFiKeyResource{} }

type iotWiFiKeyModel struct {
	Tenant        types.String `tfsdk:"tenant"`
	Name          types.String `tfsdk:"name"`
	TrustClass    types.String `tfsdk:"trust_class"`
	SSID          types.String `tfsdk:"ssid"`
	VLAN          types.Int64  `tfsdk:"vlan"`
	PSK           types.String `tfsdk:"psk"`
	Status        types.String `tfsdk:"status"`
	SecretsStored types.Bool   `tfsdk:"secrets_stored"`
	Present       types.Bool   `tfsdk:"present"`
}

func (r *iotWiFiKeyResource) Metadata(_ context.Context, req resource.MetadataRequest, resp *resource.MetadataResponse) {
	resp.TypeName = req.ProviderTypeName + "_iot_wifi_key"
}

func (r *iotWiFiKeyResource) Schema(_ context.Context, _ resource.SchemaRequest, resp *resource.SchemaResponse) {
	resp.Schema = schema.Schema{
		MarkdownDescription: "A Wi-Fi key for the tenant's IoT devices, bound to its trust class's VLAN.\n\n" +
			"Flash devices with `ssid` and `psk`. One key serves every device the tenant flashes " +
			"with it.\n\n" +
			"**Replacing this resource issues a new key, and every device already flashed with the " +
			"old one stops associating until it is reflashed.** A rebuilt API does not do that: it " +
			"restores the key from this state. Use `-replace` only when you mean to revoke.",
		Attributes: map[string]schema.Attribute{
			"tenant": schema.StringAttribute{
				Required:      true,
				PlanModifiers: []planmodifier.String{stringplanmodifier.RequiresReplace()},
			},
			"name": schema.StringAttribute{
				Required:            true,
				MarkdownDescription: "A label for the key, unique within the tenant.",
				PlanModifiers:       []planmodifier.String{stringplanmodifier.RequiresReplace()},
			},
			"trust_class": schema.StringAttribute{
				Required: true,
				MarkdownDescription: "`iot` for devices whose firmware the tenant controls, " +
					"`iot_vendor` for devices whose vendor does. The VLAN follows from this and " +
					"cannot be chosen. Changing it replaces the key, because every device holding " +
					"the old one would otherwise move VLAN silently.",
				PlanModifiers: []planmodifier.String{stringplanmodifier.RequiresReplace()},
			},
			"ssid": computedString("The SSID to flash devices with. Do not hardcode it: the same " +
				"trust class is a different SSID at another site."),
			"status": computedString("`ready` once the key is on the wireless controller."),
			"vlan":   computedInt("The VLAN this key puts a device on. Chosen by the API from the trust class."),
			"psk": schema.StringAttribute{
				Computed:  true,
				Sensitive: true,
				MarkdownDescription: "The password to flash devices with. Generated by the API; " +
					"this state holds the authoritative copy.",
				PlanModifiers: []planmodifier.String{stringplanmodifier.UseStateForUnknown()},
			},
			"secrets_stored": schema.BoolAttribute{
				Computed:            true,
				Default:             booldefault.StaticBool(true),
				MarkdownDescription: "False when the API can no longer read its copy of the key. The next apply resupplies it.",
			},
			"present": schema.BoolAttribute{
				Computed:            true,
				Default:             booldefault.StaticBool(true),
				MarkdownDescription: "Whether the API still holds this key.",
			},
		},
	}
}

func (r *iotWiFiKeyResource) Configure(_ context.Context, req resource.ConfigureRequest, resp *resource.ConfigureResponse) {
	r.client = clientFrom(req.ProviderData, &resp.Diagnostics)
}

// ModifyPlan turns "the API no longer has this key" into a diff, the way the
// workload resource does - otherwise an apply after the registry was lost
// reports no changes and the key stays unrecorded.
//
// The one deliberate difference: psk is NOT blanked. The value in state is the
// credential the devices were flashed with, so leaving it known carries it into
// the apply, the POST supplies it, and the controller is made to match the
// devices. Blanking it would make the API mint a new key and every flashed
// device would fall off the air - the opposite of what a restore is for
// (ADR-0012 §5).
func (r *iotWiFiKeyResource) ModifyPlan(ctx context.Context, req resource.ModifyPlanRequest, resp *resource.ModifyPlanResponse) {
	if req.State.Raw.IsNull() || req.Plan.Raw.IsNull() {
		return
	}
	var state iotWiFiKeyModel
	resp.Diagnostics.Append(req.State.Get(ctx, &state)...)
	if resp.Diagnostics.HasError() {
		return
	}
	// Either the key is gone, or the API holds one it can no longer read. Both
	// are put right by re-posting the key this state holds.
	lost := state.Present.Equal(types.BoolValue(false)) || state.SecretsStored.Equal(types.BoolValue(false))
	if !lost {
		return
	}
	var plan iotWiFiKeyModel
	resp.Diagnostics.Append(req.Plan.Get(ctx, &plan)...)
	if resp.Diagnostics.HasError() {
		return
	}
	plan.Present = types.BoolUnknown()
	plan.SecretsStored = types.BoolUnknown()
	plan.Status = types.StringUnknown()
	plan.SSID = types.StringUnknown()
	plan.VLAN = types.Int64Unknown()
	resp.Diagnostics.Append(resp.Plan.Set(ctx, plan)...)
}

func (r *iotWiFiKeyResource) Create(ctx context.Context, req resource.CreateRequest, resp *resource.CreateResponse) {
	var plan iotWiFiKeyModel
	resp.Diagnostics.Append(req.Plan.Get(ctx, &plan)...)
	if resp.Diagnostics.HasError() {
		return
	}
	resp.Diagnostics.Append(r.put(ctx, plan, &resp.State)...)
}

func (r *iotWiFiKeyResource) Update(ctx context.Context, req resource.UpdateRequest, resp *resource.UpdateResponse) {
	var plan iotWiFiKeyModel
	resp.Diagnostics.Append(req.Plan.Get(ctx, &plan)...)
	if resp.Diagnostics.HasError() {
		return
	}
	resp.Diagnostics.Append(r.put(ctx, plan, &resp.State)...)
}

// Read never removes the resource from state: this state holds the only copy of
// the credential the devices were flashed with, so dropping it would lose the
// key for good. It records that the API no longer has it, and ModifyPlan turns
// that into an apply that puts it back.
func (r *iotWiFiKeyResource) Read(ctx context.Context, req resource.ReadRequest, resp *resource.ReadResponse) {
	var state iotWiFiKeyModel
	resp.Diagnostics.Append(req.State.Get(ctx, &state)...)
	if resp.Diagnostics.HasError() {
		return
	}
	k, err := r.client.GetWiFiKey(ctx, state.Tenant.ValueString(), state.Name.ValueString())
	switch {
	case errors.Is(err, client.ErrNotFound):
		state.Present = types.BoolValue(false)
		resp.Diagnostics.Append(resp.State.Set(ctx, state)...)
		return
	case err != nil:
		resp.Diagnostics.AddError("Reading the Wi-Fi key failed", err.Error())
		return
	}
	// A read does not return the psk, so the one in state is kept.
	resp.Diagnostics.Append(resp.State.Set(ctx, wifiKeyFrom(k, state))...)
}

func (r *iotWiFiKeyResource) Delete(ctx context.Context, req resource.DeleteRequest, resp *resource.DeleteResponse) {
	var state iotWiFiKeyModel
	resp.Diagnostics.Append(req.State.Get(ctx, &state)...)
	if resp.Diagnostics.HasError() {
		return
	}
	err := r.client.DeleteWiFiKey(ctx, state.Tenant.ValueString(), state.Name.ValueString())
	if err != nil && !errors.Is(err, client.ErrNotFound) {
		resp.Diagnostics.AddError("Revoking the Wi-Fi key failed", err.Error())
	}
}

func (r *iotWiFiKeyResource) put(ctx context.Context, m iotWiFiKeyModel, state stateSetter) diagList {
	req := client.PutWiFiKeyRequest{
		Name:       m.Name.ValueString(),
		TrustClass: m.TrustClass.ValueString(),
	}
	// Send the key we already hold, so the API adopts it rather than minting a
	// new one. Empty on a first apply, which is when the API generates it.
	if !m.PSK.IsUnknown() && !m.PSK.IsNull() {
		req.PSK = m.PSK.ValueString()
	}
	k, err := r.client.PutWiFiKey(ctx, m.Tenant.ValueString(), req)
	if err != nil {
		var diags diagList
		diags.AddError("Issuing the Wi-Fi key failed", err.Error())
		return diags
	}
	return state.Set(ctx, wifiKeyFrom(k, m))
}

// wifiKeyFrom folds an API answer into the model, keeping the psk already in
// state when the answer carries none - a read never returns it.
func wifiKeyFrom(k client.WiFiKey, prior iotWiFiKeyModel) iotWiFiKeyModel {
	psk := prior.PSK
	if k.PSK != "" {
		psk = types.StringValue(k.PSK)
	}
	return iotWiFiKeyModel{
		Tenant:        types.StringValue(k.Tenant),
		Name:          types.StringValue(k.Name),
		TrustClass:    types.StringValue(k.TrustClass),
		SSID:          types.StringValue(k.SSID),
		VLAN:          types.Int64Value(k.VLAN),
		PSK:           psk,
		Status:        types.StringValue(k.Status),
		SecretsStored: types.BoolValue(k.SecretsStored),
		Present:       types.BoolValue(true),
	}
}
